import {build} from 'esbuild';
import {mkdir,readFile,writeFile,cp,rm} from 'node:fs/promises';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import postcss from 'postcss';
const here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,'..'),out=resolve(here,'dist');
await mkdir(out,{recursive:true});
const built=await build({absWorkingDir:here,entryPoints:['src/main.tsx'],outfile:'dist/main.js',bundle:true,format:'cjs',platform:'node',target:'es2022',external:['obsidian','electron'],minify:true,metafile:true,legalComments:'eof',logLevel:'info',define:{'process.env.NODE_ENV':'"production"'}});
await rm(resolve(out,'main.css'),{force:true});
await writeFile(resolve(out,'build-meta.json'),JSON.stringify(built.metafile,null,2));
const diff=postcss.parse(await readFile(resolve(root,'src/ui/xml-diff.css'),'utf8'));
diff.walkRules(rule=>{rule.selectors=rule.selectors.map(selector=>'.feishu-doc-local-sync-modal '+selector);});
await writeFile(resolve(out,'styles.css'),diff.toString()+'\n'+await readFile(resolve(here,'src/styles.css'),'utf8'));
for(const name of ['manifest.json','README.md'])await cp(resolve(here,name),resolve(out,name));
for(const name of ['LICENSE','THIRD_PARTY_NOTICES.md','licenses'])await cp(resolve(root,name),resolve(out,name),{recursive:true});
console.log('Optional CLI sync plugin ready: obsidian-sync-plugin/dist/');
